# Generated by Django 2.1.4 on 2019-01-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190108_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Product',
        ),
    ]
